name: Build Modules
on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true

  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Update config
        if: ${{ inputs.from_ci }}
        run: |
          if git checkout origin/update build.md; then
            UPDATE_CFG=$(./build.sh config.toml --config-update)
            if [ "$UPDATE_CFG" ]; then
              echo "$UPDATE_CFG" > config.json
            fi
          fi

      - name: Build modules/APKs
        run: if [ -f "config.json" ]; then ./build.sh config.json; else ./build.sh config.toml; fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY

      - name: Get output
        id: get_output
        run: |
          DELIM="$(openssl rand -hex 3)"

          if find build | grep -q .*rvx.apk; then
          echo "RVX_LOG<<${DELIM}${DELIM}" >> "$GITHUB_OUTPUT"
          grep -Pom1 '(?<=x: ).*' build.md >> "$GITHUB_OUTPUT"
          echo '[Changelog](https://github.com/inotia00/revanced-patches/releases/tag/v'$(grep -Pom1 '(?<=0\/patches-).*(?=\.rvp)' build.md)')' >> "$GITHUB_OUTPUT"
          echo CLI: inotia00 $(grep -Pom1 '(?<=0\/revanced-cli-).*(?=-all\.jar)' build.md) >> "$GITHUB_OUTPUT"
          echo Patches: inotia00 $(grep -Pom1 '(?<=0\/patches-).*(?=\.rvp)' build.md) >> "$GITHUB_OUTPUT"
          echo "Install [Microg](https://github.com/ReVanced/GmsCore/releases) for non-root YouTube" >> "$GITHUB_OUTPUT"
          echo "${DELIM}${DELIM}" >> "$GITHUB_OUTPUT"; fi

          if find build | grep -q .*rv.apk; then
          echo "RV_LOG<<${DELIM}${DELIM}${DELIM}" >> "$GITHUB_OUTPUT"
          grep -Pom1 '(?<=v: ).*' build.md >> "$GITHUB_OUTPUT"
          echo '[Changelog](https://github.com/ReVanced/revanced-patches/releases/tag/v'$(grep -Pom1 '(?<=d\/patches-).*(?=\.rvp)' build.md)')' >> "$GITHUB_OUTPUT"
          echo CLI: ReVanced $(grep -Pom1 '(?<=d\/revanced-cli-).*(?=-all\.jar)' build.md) >> "$GITHUB_OUTPUT"
          echo Patches: ReVanced $(grep -Pom1 '(?<=d\/patches-).*(?=\.rvp)' build.md) >> "$GITHUB_OUTPUT"
          echo "Install [Microg](https://github.com/ReVanced/GmsCore/releases) for non-root YouTube" >> "$GITHUB_OUTPUT"
          echo "${DELIM}${DELIM}${DELIM}" >> "$GITHUB_OUTPUT"; fi

          if find build | grep -q .*rvx-a6-7.apk; then
          echo "RVX_A6_7_LOG<<${DELIM}${DELIM}${DELIM}${DELIM}" >> "$GITHUB_OUTPUT"
          grep -Pom1 '(?<=7: ).*' build.md >> "$GITHUB_OUTPUT"
          echo '[Changelog](https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v'$(grep -Pom1 '(?<=1\/patches-).*(?=\.rvp)' build.md)')' >> "$GITHUB_OUTPUT"
          echo CLI: inotia00 $(grep -Pom1 '(?<=0\/revanced-cli-).*(?=-all\.jar)' build.md) >> "$GITHUB_OUTPUT"
          echo Patches: kitadai31 $(grep -Pom1 '(?<=1\/patches-).*(?=\.rvp)' build.md) >> "$GITHUB_OUTPUT"
          echo "Install [Microg](https://github.com/ReVanced/GmsCore/releases) for non-root YouTube" >> "$GITHUB_OUTPUT"
          echo "${DELIM}${DELIM}${DELIM}${DELIM}" >> "$GITHUB_OUTPUT"; fi
          
          echo "RVX_TAG=$(grep -Pom1 '(?<=0\/patches-).*(?=\.rvp)' build.md)-rvx" >> "$GITHUB_OUTPUT"
          echo "RV_TAG=$(grep -Pom1 '(?<=d\/patches-).*(?=\.rvp)' build.md)-rv" >> "$GITHUB_OUTPUT"
          echo "RVX_A6_7_TAG=$(grep -Pom1 '(?<=1\/patches-).*(?=\.rvp)' build.md)-rvx-a6-7" >> "$GITHUB_OUTPUT"
          
          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
          cat build.md >> "$GITHUB_OUTPUT"
          echo "${DELIM}" >> "$GITHUB_OUTPUT"
          cp -f build.md build.tmp

      - name: Upload rvx-a6-7 to release
        if: ${{ steps.get_output.outputs.RVX_A6_7_LOG != '' }}
        uses: svenstaro/upload-release-action@v2
        with:
          body: ${{ steps.get_output.outputs.RVX_A6_7_LOG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*rvx-a6-7.apk
          release_name: ReVanced Extended Android6-7
          tag: ${{ steps.get_output.outputs.RVX_A6_7_TAG }}
          file_glob: true
          overwrite: true
          make_latest: false

      - name: Upload rv to release
        if: ${{ steps.get_output.outputs.RV_LOG != '' }}
        uses: svenstaro/upload-release-action@v2
        with:
          body: ${{ steps.get_output.outputs.RV_LOG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*rv.apk
          release_name: ReVanced
          tag: ${{ steps.get_output.outputs.RV_TAG }}
          file_glob: true
          overwrite: true
          make_latest: false

      - name: Upload rvx to release
        if: ${{ steps.get_output.outputs.RVX_LOG != '' }}
        uses: svenstaro/upload-release-action@v2
        with:
          body: ${{ steps.get_output.outputs.RVX_LOG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*rvx.apk
          release_name: ReVanced Extended
          tag: ${{ steps.get_output.outputs.RVX_TAG }}
          file_glob: true
          overwrite: true
          make_latest: true

      - name: Update changelog
        id: update_config
        run: |
          git checkout -f update || git switch --discard-changes --orphan update
          cp -f build.tmp build.md

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: update
          file_pattern: build.md
   
      - name: Delete older releases rv
        if: ${{ steps.get_output.outputs.RV_LOG != '' }}
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 2
          delete_tag_pattern: "rv$"
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Delete older releases rvx-a6-7
        if: ${{ steps.get_output.outputs.RVX_A6_7_LOG != '' }}
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 2
          delete_tag_pattern: "rvx-a6-7"
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete older releases rvx
        if: ${{ steps.get_output.outputs.RVX_LOG != '' }}
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 2
          delete_tag_pattern: "rvx$"
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
